import JSZip from 'jszip';

export async function POST(req) {
    try {
        const { code, language, projectName, endpoints = [] } = await req.json();

        if (!code) {
            return new Response(JSON.stringify({ error: 'No code provided' }), { status: 400 });
        }

        const name   = projectName || 'agni-project';
        const isNode = language !== 'python';
        const zip    = new JSZip();
        const folder = zip.folder(name);

        // ── Main Code File ──────────────────────────────────────────────────
        const mainFile = isNode ? 'index.js' : 'main.py';
        folder.file(mainFile, code);

        // ── Package manifest ────────────────────────────────────────────────
        if (isNode) {
            folder.file('package.json', JSON.stringify({
                name,
                version: '1.0.0',
                description: `Generated by AGNI V6 — ${new Date().toISOString()}`,
                main: 'index.js',
                scripts: { start: 'node index.js' },
                dependencies: { express: '^4.18.2', cors: '^2.8.5' },
            }, null, 2));
        } else {
            const deps = ['flask', 'flask-cors', 'requests'];
            folder.file('requirements.txt', deps.join('\n') + '\n');
        }

        // ── README ──────────────────────────────────────────────────────────
        const endpointList = endpoints.length > 0
            ? '\n## API Endpoints\n\n' + endpoints.map(e => `- \`${e.method} ${e.path}\``).join('\n')
            : '';

        folder.file('README.md', `# ${name}

> Generated by **AGNI V6** on ${new Date().toLocaleDateString()}

## Setup

\`\`\`bash
${isNode ? 'npm install\nnpm start' : 'pip install -r requirements.txt\npython main.py'}
\`\`\`
${endpointList}

## Notes
- This project was AI-generated. Review before deploying to production.
`);

        // ── .gitignore ──────────────────────────────────────────────────────
        folder.file('.gitignore', isNode
            ? 'node_modules/\n.env\n*.log\n'
            : '__pycache__/\n.env\n*.pyc\n');

        // ── Generate ZIP buffer ─────────────────────────────────────────────
        const zipBuffer = await zip.generateAsync({ type: 'nodebuffer', compression: 'DEFLATE' });
        const filename  = `${name.replace(/[^a-z0-9_-]/gi, '_')}.zip`;

        return new Response(zipBuffer, {
            status: 200,
            headers: {
                'Content-Type': 'application/zip',
                'Content-Disposition': `attachment; filename="${filename}"`,
                'Content-Length': zipBuffer.length.toString(),
            },
        });
    } catch (err) {
        console.error('[export] Error:', err);
        return new Response(JSON.stringify({ error: err.message }), { status: 500 });
    }
}
